### ISSUE TITLE
Map button: configurable if opening OSMDashboard or any application supporting OPEN for GPX/KML

### ISSUE THREAD

**Issue by nutpantz** [OpenTracksApp/OpenTracks#1146]
Using open tracks 3.25 and osm dashboard 2.13 from fdroid on a pixel 6 with Android 12 feb update. There is no option to pick open dashboard to view my track (after picking the map icon i in the upper right screen of you rem tracks). I have the options of open tracks, gps statues status, and osmand (which will show my track from open tracks). There is no option to view it in osm dashboard.

I think i remember picking gpx the first time i tried to view the map but it never asked me what format again.(so that may be my faulty memory and bring in a rush to do 4 things at once)

I expect this is an issue with osm dashboard not being considered a receiver of this data type since i can view the data in osmmaps.

**Comment by dennisguse** [comment]
I am ok, with removing this functionality. It is a leftover from before OSMDashboard times... And opening the data as a file cannot be used for live updates.

@rgmf @pstorch

**Comment by pstorch** [comment]
How do we open the track in Osmand or other map app then? The share button doesn't activate them.

**Comment by nutpantz** [comment]
I think it would be nice if it was a setting for the map button. I can see the use for the various options.

**Comment by eliotb** [comment]
I seem to have same issue. The ONLY option I get when clicking the map button is to open using ... OpenTracks (as KML)
I have osmand installed.  
My current workaround is to set Instant export, and set the Track export directory to OSMAnd's own tracks directory. `Android/data/net.osmand.plus/files/tracks`  . Then at least I can choose the track(s) to display from OSMAnd

**Comment by pstorch** [comment]
> The ONLY option I get when clicking the map button is to open using ... OpenTracks (as KML)

What options do you get next after "OpenTracks (as KML)? 
"OpenTracks (as GPX)" is not available?

**Comment by eliotb** [comment]
> What options do you get next after "OpenTracks (as KML)?
> "OpenTracks (as GPX)" is not available?

The ONLY option is KML, there is no other option.

**Comment by pstorch** [comment]
And what happens when you click on KML? There should be another app chooser coming next. 

Have you tried this: 
> Please go to the app info (long click on launcher icon), then Defaults/ Set as default, then clear defaults.

**Comment by eliotb** [comment]
> There should be another app chooser coming next.

:bulb:  Ahhh right - thanks. There is. I never clicked because I was already using OpenTracks, and it made no sense to me that I would want to use OT to open its own track. This IS confusing I think.

So clicking the map button I get 
```
Complete action using OpenTracks
               Just once   Always
Use a different app
() OpenTracks
   Open as KML
```
Top one gives me Open as gpx, and offers OsmAnd+ or OpenTrac...
Bottom one gives me Open as kml, and offers OsmAnd+ or OpenTrac... or Magic Ea...

I'm pretty sure (quite a long time ago) I would click the map icon and go directly to OsmAnd...

**Comment by pstorch** [comment]
At the moment OT itself is listening on the `Intent.OpenTracks-Dashboard` Intents.
What do you think of changing this to a custom IntentChooser with these Options:
- KMZ (with and without photos)
- KML (with and without photos)
- GPX
- OpenTracks-Dashboard

In short all supported file formats + Dashboard with the option to set a default (which should be reset-able in OT settings).
This would flatten the options to choose from and could be (re-)configured within OT.

At the moment the share button uses the export file format. I'm thinking of making this configuration independent. Because a user might want to (auto-)export all tracks as KMZ with photos, but wants to share a GPX now and then.

**Comment by dennisguse** [comment]
Sounds good to me.

**Comment by pstorch** [comment]
Then I'll work on a PR with a proposal for this.
