### ISSUE TITLE
Something (scale?) wrong with elevation graphs

### ISSUE THREAD

**Issue by eliotb** [OpenTracksApp/OpenTracks#1241]
![Screenshot_20220520-211636_OpenTracks](https://user-images.githubusercontent.com/421383/169503376-89b38b1f-fb4f-4df4-b81f-974fdaecd455.png)

The elevation graph does not correspond to the track, both in by time and by distance views.
Both horizontal and vertical scale of graph vs grid seem very wrong - see screenshot.
The marker pin was placed when at the highest elevation.  (Pin time seems right, elevation wrong)
The track was a loop that started and finished at the same point.
When viewed in osmand, the exported track is a complete loop, and the elevation is correct. The highest point is about 480m.

The speed graph seems correct (slower uphill until the marker pin, faster downhill after marker)

**To Reproduce**
View graphs for any track.

If applicable:

**Technical information**
 - Device: samsung s9+
 - OS: /e/ OS  - Android 10 - 20220406
 - OpenTracks version: v3.27.0

**Comment by dennisguse** [comment]
Thanks for the report.
Some things:
* in the UI OpenTracks presents elevation as EGM2008 (more or less sea level) while the GPS/export provides WGS84.
  Most other applications present just WGS84 - so an offset is expected.
* the marker is always shown on top and not at the computed elevation (if I remember correctly).

Anyhow, the elevation plot should look different if you did a loop.
We apply some filtering to the elevation (as it is noisy due to GPS) - this removes the spikes, but it should look different.

Did you notice this with previous versions as well?

**Comment by eliotb** [comment]
![Screenshot_20220521-211314_OsmAnd+](https://user-images.githubusercontent.com/421383/169644867-917289ce-b3c4-462a-b10b-6608a1bd128f.png)
here is the track opened in osmand, with elevation profile as expected

It has been a problem for a little while, sorry i cant be specific about when i first noticed it

**Comment by dennisguse** [comment]
I have checked some of my recordings and some of them feel incorrect in the diagram.
They do not go back down to starting elevation although they should have.

This will need some investigation...
Problem might be in the TrackStatisticsUpdater.

**Comment by frasty** [comment]
Just checked and the elevation graph does not correspond to the real eleavation in most of my workouts. Tbh, I find this level of graph smoothing unnecessary. Maybe it would be helpful in this regard if the y-axis could be scaled down more proprortionally to distance/time.


![Screenshot_2022-05-24-14-34-50-25_8cd9656eedb0a8fea9f89ba34766622d](https://user-images.githubusercontent.com/622559/170041826-a6c28f03-c4bf-457e-9415-b271f9ed2660.jpg)
![Screenshot_2022-05-24-14-37-00-21_8cd9656eedb0a8fea9f89ba34766622d](https://user-images.githubusercontent.com/622559/170042007-32c2534b-c85e-481f-bb08-b0452450979e.jpg)

Compared to GPX Viewer app:
![GPX Viewer](https://user-images.githubusercontent.com/622559/170042026-05947ab6-ab01-4d63-a235-0d0bea444234.jpg)

**Comment by frasty** [comment]
As a second thought, I see that GPX Viewer shows the graphs in WGS84 proj, but the problem here is another I think, as the peak elevation differs way more than the difference between WGS84 and EGM2008.

**Comment by dennisguse** [comment]
That doesn't sound good. At least the difference should be almost identical.
Might be a problem in the rendering of the diagram / scale as well.
And the smoothing might be a problem.


Anyhow, more than one thing seems to be broken.

**Comment by InvncibiltyCloak** [comment]
Hopefully this is helpful. I have compared the GPX export from OpenTracks vs the plot shown in OpenTracks GUI and the two  definitely do not match at all.

I ran the GPX through Python to get the plot shown, so there is no other software mucking with the elevation data in the GPX. The trail was a there and back, so the final elevation should approximately match start elevation (other than not starting the track immediately). 

Because the Python plot appears to be correct, OpenTracks appears to be recording the correct data, it is just displaying it incorrectly. Hope this helps narrow things down.

I have seen the same result for multiple hikes, where the there-and-back hike ends at an elevation very different from the start elevation. They typically end somewhere close to the average elevation during the hike, (which to me suggests a problem in the filtering).

![Screenshot_20220610-131632_OpenTracks](https://user-images.githubusercontent.com/8410437/173135300-1aed703c-0190-4a37-abde-d76bd454314c.png)
![plot](https://user-images.githubusercontent.com/8410437/173135378-54873237-0049-444d-83a7-19e0d33a6108.png)

**Comment by dennisguse** [comment]
Found the problem: for the diagrams only, we have some code that smoothes the altitude.
And that doesn't work properly.

Removing the smoothing solves the issue.
![image](https://user-images.githubusercontent.com/2820825/173187594-1f9b7ccc-ef53-4ff3-b418-534ea4a67252.png)
