### ISSUE TITLE
Export accuracy in GPX file as a relation of hdop value (to use in Josm)

### ISSUE THREAD

**Issue by brunetton** [OpenTracksApp/OpenTracks#1438]
Sorry, this is more a question than a FR, but I don't know where to ask

**Is your feature request related to a problem? Please describe.**
I'm trying to use OpenTracks exported gps log file in Josm to map; **with** an accuracy information. I'm using GPX format because, as far as I can see, this information is not present at all in KMZ exported files.

But opening the exported GPX file in Josm, and activating [accuracy indicator](https://help.openstreetmap.org/questions/59662/show-gpx-accuracy-hdop-in-editor) in Josm doesn't show any accuracy indication.

I searched a little and seen that the accuracy is not implemented in [GPX 1.1](http://www.topografix.com/GPX/1/1/). But `hdop`, `vdop`, and `pdop` are. And for some reasons Josm seem to only use `hdop` value for drawing accuracy circles.

**Describe the solution you'd like**
I'd like to be able to use the exported `accuracy_horizontal` and `accuracy_vertical` that are currently exported as an extension to GPX format (`gpxtpx:TrackPointExtension`) in Josm

**Solutions ?**
- I suppose exported accuracy comes from NMEA messages; am I right ?
- is it possible to compute and export hdop and vdop values from accuracy value ? Would it represent anything at all ?
- by manually adding `<hdop>` to `<trkpt>` and measuring drawn circles in Josm; I empirically deduced that `accuracy = hdop x 4.3`. Is this 4.3 kind of "standard" ?

Sorry again to post here; but I'm not sure:
- if I should ask here
- if I should ask to Josm team to add support for `accuracy_horizontal` and `accuracy_vertical` in `gpxtpx:TrackPointExtension`
- if I should ask to GPX team to add an "accuracy" value in format (and does it makes sense anyway ?)
- if I should not ask to anybody because all of this is non-sense !

Thanks for reading and your time. And thanks for this great peace of software !

**Comment by dennisguse** [comment]
Really good question!

OpenTracks stores the `accuracy_horizontal` and `accuracy_vertical` as provided by the `LocationManager`:
`
Returns the estimated horizontal accuracy radius in meters of this location at the 68th percentile confidence level. This means that there is a 68% chance that the true location of the device is within a distance of this uncertainty of the reported location.
`
Taken from here: https://developer.android.com/reference/android/location/Location#getAccuracy()

This is neither hdop, vdop, pdop.... but it is likely extracted from NMEA.
More information is not provided by the LocationMananger - likely because must be able to provide Network-based estimations etc (best guess).
And there is no GPX standard for accuracy_horizontal and accuracy_vertical.

And OpenTracks does not parse NMEA (yet); it is a separate callback and requires parsing the data manually (and merging it to the provided `Location`).
We might be able to get some functionality from GPSTest: https://github.com/barbeau/gpstest/blob/9f294a4ffc603045a1b84a2efb861449b143aefa/GPSTest/src/main/java/com/android/gpstest/util/NmeaUtils.java

I guess parsing NMEA would be the right thing to do in OpenTracks before we create another standard...
Does this help?
