### ISSUE TITLE
Using the code

### ISSUE THREAD

**Issue by ugintl** [OpenTracksApp/OpenTracks#1548]
Can I upload the app to my play store with my own name?

**Comment by ugintl** [comment]
Yes I will modify it

**Comment by pstorch** [comment]
@ugintl you will also do support for your fork then?
Beware that you might have to justify against Google, if your app is too similar. They check for duplicates and rip offs.

**Comment by ugintl** [comment]
I will make sure my app is different than yours. While checking for duplicates what Google focuses on?

**Comment by dennisguse** [comment]
@ugintl what would you like to change?
And why can this not be integrated into OpenTracks?

Are you planning a hard fork or do you plan to pull changes from OpenTracks in the future?

Who is your user base?

**Comment by dennisguse** [comment]
@ugintl that does not really answer the question, why would want to you want to do :man_shrugging: 

Anyhow:
* Code is open source (Apache license) and you have to adhere to it
* You have to use a different logo (otherwise might be flagged later by PlayStore)
* You should use a different application name
* You should make clear that is NOT OpenTracks (and note somewhere visible for the user a fork)

To be honest, I still didn't understand why you want to do this.
Please keep in mind that creating a fork (which this is likely going to be), might have some severe side effects.
Some discussions here: 
https://softwareengineering.stackexchange.com/a/253940
