### ISSUE TITLE
When importing gpx workouts, the statistics are missing (important for the athlete) heart rate (min.max.average)

### ISSUE THREAD

**Issue by snooppr** [OpenTracksApp/OpenTracks#1588]
There is a graph for the pulse, but it's meaningless (no % in zones, no connecting, minimum, maximum values)

In general, for an athlete, there is not enough in the statistics: number of steps;  min.max.  total climb;  pulse;  calories burned.  
This lack defines a sports track from a simple tracker.

**Comment by snooppr** [comment]
About height.  The same track in open source, fito track calculation shows no in OT.

![OT and FT](https://github.com/OpenTracksApp/OpenTracks/assets/61022210/c178155e-bf39-44f0-97fd-4c5be5a55e83)

**Comment by snooppr** [comment]
@dennisguse HI, 
> If you have time, both things just wait for somebody to implement them.

Perhaps the question will seem strange, but why does the developer hope that someone else implements the main functionality for OT, but not himself?  (OT is advertised as a sports tracker, which is confusing when migrating).  From the point of view of open source, this is almost the norm, but from the point of view of the user, it is not the norm.

**Comment by dennisguse** [comment]
Free as in speech not as in beer.

I build things in my spare time and if this accidentally is useful to somebody else, this is a bonus. 
If somebody proposes something that I like to build (because personal reasons), I might build it. 
If not then not.

Why others  contribute (code or translations or whatever) is their concern. 

If you really want something done, you either need to do it yourself or motivate others to do it for you. 

PS I would be available as a (paid) freelancer
