### ISSUE TITLE
Closed issue #1673 (extreme gain and loss in elevation) persists on Google Pixel 7 Pro

### ISSUE THREAD

**Issue by KreMic** [OpenTracksApp/OpenTracks#1744]
**Describe the bug**
Closed issue #1673 (extreme gain and loss in elevation) persists on Google Pixel 7 Pro
On rather plane ground you get about thousands of meters of ascend and descend.
I realized this problem with different Opentrack versions prior to 4.9 already under Android 13

**To Reproduce**
1. Start Opentracks
2. Record a track
3. End track
4. See enormous amounts in ascend and  descend

**Technical information**
 - Device: Google Pixel 7 Pro [2022[
 - OS: Android 14 Patchlevel Oct 5 2023
 - OpenTracks version: 4.9.1

**Comment by dennisguse** [comment]
Same answer as in #1673: it is a problem with the sensor in your phone.
Since OpenTracks uses the barometer alone for gain/loss, there is no real way around this.
One option would be to use barometer and GPS and implement sensor fusion, but that is really complicated.

If you want to play around, you can try to implement some advanced filtering of the data.
... but the sensor is still broken or something preventing it from measuring accurately.

:shrug:
