### ISSUE TITLE
Remove show on map as KML/GPX

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#2012]
I guess, the feature "show on map behavior" can be removed by allowing the dashboard API only. 
For some users, this feature has been confusing (One example below).  

Also, the implementation is relatively complicated (data provider with inheritance). 

https://play.google.com/console/developers/6689313037175729079/app/4973886958180230950/user-feedback/review-details?reviewId=b8629be4-62d8-4591-8042-cd06b4853011&corpus=PUBLIC_REVIEWS

@pstorch what do you think?

**Comment by pstorch** [comment]
Sounds good to me. KML/GPX can still be used via the share function.

**Comment by shadow00** [comment]
@pstorch Do you mean this share button? ![](https://i.imgur.com/wH8Yyn8.jpeg)

Because if so, then osmAnd doesn't show up as a possible recipient for me - i.e. I'd have to export a track to some external storage app, and then import that into osmAnd.

Now that I look at it, I don't see my phone's internal storage as an option either - so I don't see a way to manually export a single track to memory (without going through a third-party app like Google Drive and such).  
The only option would be to exporting them all by setting the local folder in the settings.  
Is this intentional?

**Comment by pstorch** [comment]
@shadow00 yes, this share button. 
Unfortunately it's a bit complicated to properly share data in android. There are several possibilities an app can share data and also several possibilities for an app to receive data.
Looks like OT shares it differently than osmAnd receive it. 
It works for example with OrganicMaps and others.

**Comment by dennisguse** [comment]
@shadow00 can you open an issue for OsmAnd?
They can just make their intent selector slightly more flexible.
