### ISSUE TITLE
Improve track deletion UI

### ISSUE THREAD

**Issue by dennisguse** [OpenTracksApp/OpenTracks#242]
TrackDeleteActivity shows a transparent background while a message is shown as a (progress) dialog.
However, the dialog just pops up and vanishes (especially if only one track is deleted).

So, we need to do something, but I am not sure how a good solutions look like.
I guess, we need to show some blocking UI, right?

**Comment by rgmf** [comment]
Yes, you are right @dennisguse, the dialog appearing and going away so quickly results in a strange effect.

I don't know, but maybe a simple spinner overlapping the ListView could be better. This way Dialog can be removed.

Other solution could be using RecyclerView instead of ListView because RecyclerView has remove/add/update animations out of the box.
