### ISSUE TITLE
Exported KMZ file contains colon - which is an illegal character for filenames on Windows

### ISSUE THREAD

**Issue by tfl** [OpenTracksApp/OpenTracks#254]
Due to a colon in the filename (for instance 2020-06-01 09:38.kmz) the file cannot be used on Windows. Use dashes please.

**Comment by dennisguse** [comment]
The filename is the actual trackname: so as a quick workaround you could change it in the settings to number instead of date.

We actually have a function for sanitizing filenames for FAT32: this: https://github.com/OpenTracksApp/OpenTracks/blob/240d8f6b6cef60b289a079d5c7621ce024ab0588/src/main/java/de/dennisguse/opentracks/util/FileUtils.java#L148

However, it is nowadays only used for pictures within KMZ files.
We reworked the whole file handling and stopped using this function as Android nowadays supports UTF8.
But you are right, we can enhance this.
