### ISSUE TITLE
Bluetooth speed sensor 

### ISSUE THREAD

**Issue by badger40** [OpenTracksApp/OpenTracks#723]
**Describe the bug**
Using a bluetooth speed / cadence sensor (model: Coospo bk467) with GPS turned off. The sensor connects to opentracks and records distance but not 'move time' 'max speed' 'avg move speed'
![Screenshot_2021-04-21-08-53-58-294_de dennisguse opentracks](https://user-images.githubusercontent.com/82934222/115518577-3abe5d80-a280-11eb-9965-0663529ba583.jpg)
[Coopo bk467 Sensor:](http://coospo.com/sensor/30.html)  

**Technical information**
 - Device: [Xiaomi Pocophone F1]
 - OS: [miglobal 12.0.3 stable]
 - Opentracks version [v13.17.1]

**Comment by dennisguse** [comment]
That is not implemented yet; OpenTracks only stores data (and does the computation) when a GPS signal is received. And if press stop/pause, but that does not go too well with the overall statistics.
Otherwise just the sensor data is shown.

More details can be found here: https://github.com/OpenTracksApp/OpenTracks/issues/500

@badger40 Can you open a PR and add the sensor you used to this file: https://github.com/OpenTracksApp/OpenTracks/blob/main/README_TESTED_SENSORS.md
