### ISSUE TITLE
Exported / Imported moving time with pause.

### ISSUE THREAD

**Issue by rgmf** [OpenTracksApp/OpenTracks#753]
**Describe the bug**
I recorded a long track and moving time not match after export/import it.

I figured it was because I paused the activity when we took a rest in the middle of the route to have a cafe. The difference between times looks like the time we took in that rest. But I've not been able to reproduce it.

The rest of stats are right.

![image](https://user-images.githubusercontent.com/4819612/117579134-de699380-b0f1-11eb-83da-2ec536fc7a2b.png)

**Comment by dennisguse** [comment]
Also, the AVG SPEED is off.

Assumption: KML/KMZ

Possible things that might not work:
* KML exporter does not export PAUSE_MANUAL correctly
* KML importer does not import PAUSE_MANUAL correctly
* (unlikely) TrackStatisticsUpdater does something wrong

All these things do not have that good a test coverage.
We might start by making ExportImportTest reproducible, i.e., using fixed and useful timestamps for the test data instead of current.

PS: Nice gain!
Which I would have any mountains close by.

**Comment by rgmf** [comment]
> Also, the AVG SPEED is off.
> 
> Assumption: KML/KMZ
> 
> Possible things that might not work:
> 
>     * KML exporter does not export PAUSE_MANUAL correctly
> 
>     * KML importer does not import PAUSE_MANUAL correctly
> 
>     * (unlikely) TrackStatisticsUpdater does something wrong
> 
> 
> All these things do not have that good a test coverage.
> We might start by making ExportImportTest reproducible, i.e., using fixed and useful timestamps for the test data instead of current.
> 

I was using GPX but I've tried exporting/importing in KML and it works well.

This issue only affects GPX files. Strange... I'll try to catch it.

> PS: Nice gain!
> Which I would have any mountains close by.

Here mountains are not very high but there are a lot of mountains :grinning:

**Comment by dennisguse** [comment]
And I guess, what it is #597 that is tracking this missing feature.
