### ISSUE TITLE
KML/KMZ/GPX Import: Moving Time and Maximum Speed not computed (but stored in TrackPoints)

### ISSUE THREAD

**Issue by vlmendz** [OpenTracksApp/OpenTracks#982]
**Describe the bug**
After import a track recorded with the Cruiser app, OpenTracks does not display the moving time and maximum speed. It was tested by exporting the track as GPX version 1.0 and 1.1 with the same result.

**To Reproduce**
Import GPX files similar to fragments shown here:

	<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
	<gpx version="1.0" creator="Cruiser" xmlns="http://www.topografix.com/GPX/1/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd">
	  <metadata>
	    <name>20210907_213944.gpx</name>
	  </metadata>
	  <trk>
	    <name>20210907_213944.gpx</name>
	    <trkseg />
	    <trkseg />
	    <trkseg>
	      <trkpt lat="30.14185982" lon="-40.3863038">
	        <ele>-5</ele>
	        <time>2021-09-07T22:10:19Z</time>
	        <hdop>4</hdop>
	        <speed>1</speed>
	      </trkpt>
	      <trkpt lat="30.14184657" lon="-40.38670089">
	        <ele>-5</ele>
	        <time>2021-09-07T22:11:07Z</time>
	        <hdop>4</hdop>
	        <speed>2</speed>
	      </trkpt>
	      ...
	      ...
         </trkseg>
       </trk>
     </gpx>

☝️GPX Version 1.0

	<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
	<gpx version="1.1" creator="Cruiser" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
	  <metadata>
	    <name>20210907_213924.gpx</name>
	  </metadata>
	  <trk>
	    <name>20210907_213924.gpx</name>
	    <trkseg />
	    <trkseg />
	    <trkseg>
	      <trkpt lat="30.14185982" lon="-40.3863038">
	        <ele>-5</ele>
	        <time>2021-09-07T22:10:19Z</time>
	        <hdop>4</hdop>
	        <extensions>
	          <speed>1</speed>
	        </extensions>
	      </trkpt>
	      <trkpt lat="30.14184657" lon="-40.38670089">
	        <ele>-5</ele>
	        <time>2021-09-07T22:11:07Z</time>
	        <hdop>4</hdop>
	        <extensions>
	          <speed>2</speed>
	        </extensions>
	      </trkpt>
	      ...
	      ...
          </trkseg>
        </trk>
      </gpx>

☝️ GPX Version 1.1

![IMG_20211014_085552](https://user-images.githubusercontent.com/91810638/137321850-87810475-70af-4cb4-8046-76913f64f006.jpg)

☝️ Statistics of imported GPX file

**Technical information**
 - Device: Redmi Note 7
 - OS: MIUI 12.5.1 (Android 10 based)
 - OpenTracks Version 3.20.2

**Comment by dennisguse** [comment]
DAMN, you are a really good tester!
Kudos!

First of all: speed is not imported from these GPX files due to #744.

BUT it should then be computed (using the previous TrackPoint in the current segment).
It happens in the TrackImporter and that works (at least something :sunglasses:).

BUT the computation of speed happens AFTER we compute the TrackStatistics (and here speed is still `null`).
So, moving time and max speed are not computed.

PS/ this affects GPX w/o speed and also KML/KMZ without speed.

@rgmf One question regarding the check for isMoving before adding the a TrackPoint to moving time.
I am not sure, I understand the reason for this (and there is no failing test case if removed; the PR has now one ><).
Do you remember the reason to add this?

https://github.com/OpenTracksApp/OpenTracks/blob/c742dae6e06f69248f9eee8327efceb4eaade17f/src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java#L181

**Comment by rgmf** [comment]
> @rgmf One question regarding the check for isMoving before adding the a TrackPoint to moving time. I am not sure, I understand the reason for this (and there is no failing test case if removed; the PR has now one ><). Do you remember the reason to add this?
> 
> https://github.com/OpenTracksApp/OpenTracks/blob/c742dae6e06f69248f9eee8327efceb4eaade17f/src/main/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdater.java#L181


If you remove that if then moving time never stop (and going on and on) that's because I added that if to update or not the moving time (it only must be update when moving is detected, right?).

**Comment by dennisguse** [comment]
@rgmf I see - because we add the time between lastTrackPoint and currentTrackPoint, we have to check if lastTrackPoint was considered moving and not only if currentTrackPoint was moving.
Then we have indirect test coverage for this now :sunglasses:
